<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Memory" targetNamespace="urn:Memory"
	xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:typens="urn:Memory"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

	<!-- Messages are the 'function' signatures -->
	<message name="getServerMemoryInfo">
		<part name="lmmSupported" type="xsd:boolean"/>
	</message>

	<message name="getServerMemoryInfoResponse">
		<part name="return" type="xsd:anyType" />
	</message>
	
	<message name="runLMMCommand">
		<part name="sql" type="xsd:string"/>
	</message>

	<message name="runLMMCommandResponse">
		<part name="return" type="xsd:anyType" />
	</message>
	
	<!--
		portType expose the services and defines their input / output routines
	-->
	<portType name="MemoryPort">
		
		<operation name="getServerMemoryInfo">
			<input  message="typens:getServerMemoryInfo" />
			<output message="typens:getServerMemoryInfoResponse" />
		</operation>
		
		<operation name="runLMMCommand">
			<input  message="typens:runLMMCommand" />
			<output message="typens:runLMMCommandResponse" />
		</operation>

	</portType>

	<!-- define protocol details for each Ports -->
	<binding name="MemoryBinding" type="typens:MemoryPort">
		<soap:binding style="rpc"
			transport="http://schemas.xmlsoap.org/soap/http" />
		
		<operation name="getServerMemoryInfo">
			<soap:operation soapAction="urn:MemoryAction" />
			<input>
				<soap:body use="encoded" namespace="urn:Memory"
					encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:Memory"
					encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>
		
		<operation name="runLMMCommand">
			<soap:operation soapAction="urn:MemoryAction" />
			<input>
				<soap:body use="encoded" namespace="urn:Memory"
					encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:Memory"
					encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>
		
	</binding>

	<service name="MemoryService">
		<port name="MemoryPort" binding="typens:MemoryBinding">
			<soap:address location="services/memory/memoryService.php" />
		</port>
	</service>
</definitions>
